"""Read-only verification of the proposed five-file byte-preservation fix."""
import datetime, hashlib, json, pathlib, subprocess
ROOT=pathlib.Path(__file__).resolve().parents[3]
OUT=pathlib.Path(__file__).resolve().parent
R='de5f30155c68755dbd5af691625a0651e3fb7230'
sha=lambda b:hashlib.sha256(b).hexdigest()
oid=lambda b:hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()
git=lambda *a:subprocess.check_output(['git',*a],cwd=ROOT)
catalog=json.loads((ROOT/'tests/fixtures/corpus.json').read_text(encoding='utf-8-sig'))
paths=['tools/test/generate_numbered_fixtures.py','tests/fixtures/numbered/manifest.json','tests/fixtures/presets/generate_presets.py','tools/test/generate_pdf_envelope_fixtures.py','tests/fixtures/presets/manifest.json']
pins={}
for group,metadata in catalog['groups'].items():
    for key in ['generator','manifest']:
        if key in metadata:pins[metadata[key]]=metadata[key+'_sha256']
checks=[]
def check(ok,label):checks.append({'check':label,'pass':bool(ok)})
check(git('rev-parse','HEAD').decode().strip()==R,'current primary HEAD is unaccepted R')
check(not git('status','--porcelain=v1'),'primary working checkout unchanged/clean')
rows=[]
for n,path in enumerate(paths):
    raw=(ROOT/path).read_bytes();stored=git('show',R+':'+path)
    desired=stored if n<4 else raw
    check(sha(desired)==pins[path],'proposed exact bytes retain existing catalogue pin: '+path)
    check(stored.count(b'\r\n')==0,'current canonical R Git blob is LF: '+path)
    if n<4:
        check(raw==stored.replace(b'\n',b'\r\n'),'only fresh checkout CRLF conversion: '+path)
        check(oid(desired)==git('rev-parse',R+':'+path).decode().strip(),'proposed original Git blob unchanged: '+path)
    else:
        check(raw.count(b'\r\n')==61 and raw==stored.replace(b'\n',b'\r\n'),'presets manifest existing pinned CRLF representation')
        check(json.loads(raw)==json.loads(stored),'presets manifest semantic JSON unchanged')
    rows.append({'path':path,'pinned_sha256':pins[path],'current_R_git_oid':git('rev-parse',R+':'+path).decode().strip(),'current_R_blob_sha256':sha(stored),'current_working_sha256':sha(raw),'proposed_git_oid':oid(desired),'proposed_raw_sha256':sha(desired),'proposed_bytes':len(desired),'proposed_CRLF':desired.count(b'\r\n'),'proposed_attribute':'-text','source_content_change':'none; exact original Git LF blob' if n<4 else 'newline representation only; commit existing pinned CRLF bytes'})
for path in ['tests/fixtures/features/generate_features.py','tests/fixtures/features/manifest.json']:
    stored=git('show',R+':'+path);raw=(ROOT/path).read_bytes()
    check(stored==raw and sha(raw)==pins[path],'existing feature pin/Git/raw equality untouched: '+path)
issues=[x for x in checks if not x['pass']]
report={'task':'T31','audit':'independent_proposed_checkout_fix_byte_contract','observed_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'base_unaccepted_R':R,'auditor_sha256':sha(pathlib.Path(__file__).read_bytes()),'result':'pass_for_proposed_contract' if not issues else 'fail','checks':len(checks),'issues':issues,'exact_five_file_contract':rows,'optional_catalogue_rule':{'recommendation':'omit for smallest fix','reason':'corpus.json is typed semantic JSON and its generation/verification receipt binds actually observed raw catalogue bytes, not an externally pinned canonical catalogue byte hash. A new explicit raw-byte stability policy could justify pinning, but is not needed for the five failing recipe/manifest expectations.'},'required_review_and_regression_criteria':['First four file Git OIDs remain identical to R; presets manifest new Git blob equals its existing pinned CRLF raw SHA and semantically equals R JSON. No catalogue/manifest expected hashes or recipe behavior weakened.','Only exact five -text path rules are added; existing feature -text/PDF binary rules retained. Preserve all whitespace checks and allow the intentional CRLF representation through cr-at-eol where needed.','Regression performs genuine Git checkout/materialization with core.autocrlf=true and false, checks all existing seven recipe/manifest raw pins and numbered generated byte expectations, and compares committed blob bytes rather than just parsed JSON.','The old unaccepted R genuinely reproduces the defect; the committed corrected source passes fresh-checkout regression and original fixture/oracle/corpus checks. Do not infer acceptance from manually normalized primary working files.','Retain strict tamper/type/order/source-safety negative tests and original failed R receipts. No user/native dependency install, elevation, global Git/policy changes or real user PDF data.','Normal reviewed fix PR and permitted merge create a new full R. Independently prove actual lineage and reviewed source delta, then full exact-R dual-shell/native/static/CI guards and clean/live main before acceptance.','Runtime, VERSION, builder, allowlist, native flags and public package documents must remain byte-identical; final package/tag/publication/download gates remain later. AC058 stays excluded/unperformed.'],'limitations':['Proposed contract review only; no source edits, checkout normalization, fresh-checkout test, application/native execution, commit, merge or acceptance of corrected R by this auditor.']}
(OUT/'checkout-fix-contract-review.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'result':report['result'],'checks':len(checks),'issues':issues,'five_paths':[x['path'] for x in rows],'presets_proposed_git_oid':rows[-1]['proposed_git_oid']},indent=2))
