# Test-only Git/ZIP fixtures. Importing definitions performs no build or app work.
function Invoke-PackageTestGit {
    param([string]$Repository, [string[]]$Arguments)
    $gitPath = (Get-Command git.exe -CommandType Application | Select-Object -First 1).Source
    $result = Invoke-TestChildProcess -Executable $gitPath -Arguments (@('-C',$Repository) + $Arguments) -TimeoutMilliseconds 15000
    if ($result.ExitCode -ne 0) { throw ('Synthetic Git command failed: ' + ($Arguments -join ' ') + ': ' + $result.Stderr) }
    if ([string]::IsNullOrEmpty($result.Stdout)) { return }
    return ($result.Stdout.TrimEnd("`r","`n") -split '\r?\n')
}

function Save-PackageTestJson {
    param([string]$Path, [object]$Value)
    [IO.File]::WriteAllText($Path, ($Value | ConvertTo-Json -Depth 10), (New-Object Text.UTF8Encoding $false))
}

function Complete-PackageTestCommit {
    param([string]$Repository)
    Invoke-PackageTestGit -Repository $Repository -Arguments @('add','--all') | Out-Null
    Invoke-PackageTestGit -Repository $Repository -Arguments @('-c','user.name=T28Synthetic','-c','user.email=t28@example.invalid','-c','core.hooksPath=NUL','commit','--quiet','--no-gpg-sign','-m','T28 synthetic package fixture') | Out-Null
    return [string](Invoke-PackageTestGit -Repository $Repository -Arguments @('rev-parse','HEAD'))
}

function New-PackageTestRepository {
    param([string]$SourceRepository, [string]$WorkRoot)
    $repository = Join-Path $WorkRoot ('repo [x] ! & ' + [Guid]::NewGuid().ToString('N'))
    [void][IO.Directory]::CreateDirectory($repository)
    $allowlist = Get-Content -LiteralPath (Join-Path $SourceRepository 'release-files.json') -Raw | ConvertFrom-Json
    $paths = @($allowlist.files) + @('release-files.json','docs/codex/PACKAGE_CONTRACT.json')
    $paths += @(Get-ChildItem -LiteralPath (Join-Path $SourceRepository 'tools/release') -Recurse -File | ForEach-Object { $_.FullName.Substring($SourceRepository.Length + 1).Replace('\','/') })
    foreach ($relative in $paths) {
        $destination = Join-Path $repository $relative
        [void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($destination))
        [IO.File]::Copy((Join-Path $SourceRepository $relative), $destination, $false)
    }
    [IO.File]::WriteAllText((Join-Path $repository '.gitignore'), "/tests/.work/`n", (New-Object Text.UTF8Encoding $false))
    # Deliberately exercise checkout CRLF versus stored Git LF bytes. LICENSE
    # preserves the project's existing exact byte contract.
    [IO.File]::WriteAllText((Join-Path $repository '.gitattributes'), "* text=auto`n/LICENSE -text`n", (New-Object Text.UTF8Encoding $false))
    Invoke-PackageTestGit -Repository $repository -Arguments @('init','--quiet') | Out-Null
    Invoke-PackageTestGit -Repository $repository -Arguments @('config','core.autocrlf','false') | Out-Null
    Invoke-PackageTestGit -Repository $repository -Arguments @('config','core.symlinks','false') | Out-Null
    $commit = Complete-PackageTestCommit -Repository $repository
    return [pscustomobject]@{ Repository=$repository; Commit=$commit; Allowlist=$allowlist }
}

function Read-PackageTestGitBlob {
    param([string]$Repository, [string]$Commit, [string]$Path)
    $start = New-Object Diagnostics.ProcessStartInfo
    $start.FileName = (Get-Command git.exe -CommandType Application | Select-Object -First 1).Source
    # All values are generated by these fixtures and cannot contain double quotes.
    $start.Arguments = '-C "' + $Repository + '" cat-file blob "' + $Commit + ':' + $Path + '"'
    $start.UseShellExecute = $false
    $start.CreateNoWindow = $true
    $start.RedirectStandardOutput = $true
    $start.RedirectStandardError = $true
    $process = New-Object Diagnostics.Process
    $process.StartInfo = $start
    $bytes = New-Object IO.MemoryStream
    try {
        if (-not $process.Start()) { throw 'Independent Git blob read failed to start.' }
        $errorText = $process.StandardError.ReadToEndAsync()
        $process.StandardOutput.BaseStream.CopyTo($bytes)
        if (-not $process.WaitForExit(15000)) { $process.Kill(); throw 'Independent Git blob read timed out.' }
        if ($process.ExitCode -ne 0) { throw ('Independent Git blob read failed: ' + $errorText.Result) }
        return ,$bytes.ToArray()
    } finally { $process.Dispose(); $bytes.Dispose() }
}

function Get-PackageTestBytesHash {
    param([byte[]]$Bytes)
    $algorithm = [Security.Cryptography.SHA256]::Create()
    try { return ([BitConverter]::ToString($algorithm.ComputeHash($Bytes))).Replace('-','').ToLowerInvariant() }
    finally { $algorithm.Dispose() }
}

function Read-PackageTestZip {
    param([string]$ZipPath)
    $zip = [IO.Compression.ZipFile]::OpenRead($ZipPath)
    try {
        return @(foreach ($entry in $zip.Entries) {
            $stream = $entry.Open()
            $buffer = New-Object IO.MemoryStream
            try { $stream.CopyTo($buffer); [pscustomobject]@{ Path=$entry.FullName; Bytes=$buffer.ToArray(); Timestamp=$entry.LastWriteTime; Attributes=$entry.ExternalAttributes } }
            finally { $stream.Dispose(); $buffer.Dispose() }
        })
    } finally { $zip.Dispose() }
}
