from pathlib import Path
import hashlib,json,runpy
repo=Path.cwd().resolve();work=repo/'tests/.work';evidence=repo/'docs/codex/evidence'
sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.loads(p.read_bytes().decode('utf-8-sig'))
original=work/'Validate-T15C2-before-normalization.py';assert not original.exists()
validator=work/'Validate-T15C2.py';raw=validator.read_bytes()
receipt=load(work/'T15-C2-staged-normalization-preparation.json');assert sha(raw)==receipt['ValidatorSourceSHA256']
original.write_bytes(raw)
text=raw.decode('utf-8');assert "len(prov['bindings'])==45" in text
text=text.replace("len(prov['bindings'])==45","len(prov['bindings'])==50").replace('Exactly45 separately archived supplemental original/public bindings','Original45 supplemental bindings plus5 records-check support bindings').replace('Exactly intended364 new evidence plus6 config records paths','Exactly intended evidence plus6 config records paths')
validator.write_bytes(text.encode('utf-8'))
B=runpy.run_path(str(work/'Collect-T15Evidence.py'),run_name='closure_privacy');sanitizer=B['T15Collector'](repo,'53d0923c95a86ae6a44bc89bab51cac6786c1e32')
prov=load(evidence/'T15-C1-review-provenance.json');assert len(prov['bindings'])==45
for leaf in ['Validate-T15C2-before-normalization.py','Validate-T15C2.py','Record-T15StagedNormalization.py','T15-C2-staged-normalization-preparation.json','Extend-T15RecordsCheckHistory.py']:
    source=work/leaf;raw=source.read_bytes();relative=source.relative_to(repo).as_posix()
    public=B['json_bytes'](sanitizer.sanitize_value(load(source))) if source.suffix=='.json' else sanitizer.sanitize_string(raw.decode('utf-8-sig')).encode('utf-8')
    target=evidence/'T15-C1-review-support'/(sha(relative.encode())[:12]+'-'+source.name);assert not target.exists()
    sanitizer.privacy_gate(public,leaf);target.write_bytes(public)
    prov['bindings'].append({'source':relative,'file':target.relative_to(repo).as_posix(),
     'classification':'records-only staged normalization preparation/check source; excluded from application acceptance',
     'raw_sha256':sha(raw),'public_sha256':sha(public),'raw_bytes':len(raw),'public_bytes':len(public),'privacy_changed_bytes':raw!=public})
prov['records_check_preparation']={'result':'initial staged completion-note byte mismatch; literal file attribute added',
 'application_change':False,'application_rerun':False,'collector317_plan_unchanged':True,
 'original_validator_source_preserved':original.relative_to(repo).as_posix(),
 'failed_check_receipt':'tests/.work/T15-C2-staged-normalization-preparation.json',
 'history':'Tool transcript records the actual exit1/traceback; separate original stdout/stderr files were not retained. Original staged bytes differed only by newline normalization. Corrected exact file attribute and final staged verification follow.'}
(evidence/'T15-C1-review-provenance.json').write_bytes(B['json_bytes'](prov))
completion=evidence/'T15-completion.md';text=completion.read_text(encoding='utf-8')
marker='## Synchronization and continuation';assert text.count(marker)==1
text=text.replace(marker,'The first records-only staged-byte check found Git normalizing line endings in this generated completion note. Literal contents were equivalent; a file-specific `-text` attribute preserves exact generated bytes. The original/final validator sources and honest failed-check receipt are bound in supplemental provenance. No application code changed or suite reran; final staged verification follows.\n\n'+marker)
completion.write_text(text,encoding='utf-8')
print(json.dumps({'result':'prepared','collector_files_unchanged':317,'supplemental_bindings':len(prov['bindings']),'application_change':False}))
