param([ValidateSet('ps51','ps7')][string]$Shell,[int]$Attempt=1)
$ErrorActionPreference='Stop'
$repo=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '../..')).ProviderPath
. (Join-Path $repo 'src/WinPDFMerge.Helpers.ps1')
$exe=if($Shell -eq 'ps51'){Join-Path $env:SystemRoot 'System32/WindowsPowerShell/v1.0/powershell.exe'}else{Join-Path $env:LOCALAPPDATA 'WinPDFMergerDevCache/T09-ps7-6719cb8d846e47c9bf69d6c7f5948a6a/portable/pwsh.exe'}
$argv=@('-NoProfile','-ExecutionPolicy','RemoteSigned','-File',(Join-Path $repo 'tools/test/Invoke-Tests.ps1'),'-Tier','ParametersNative','-PesterModulePath',(Join-Path $env:USERPROFILE '.cache/WinPDFMerger-T03/pester-6.2.0-fe69858b0b7b4b92ae85caf8dd8fcc67/module/Pester.psd1'),'-PdftkPath',(Join-Path $env:LOCALAPPDATA 'WinPDFMergerDevCache/T03-pdftk-295456f881ea41a4a78dcf207f8965bf/pdftk-server-2.02/app/bin/pdftk.exe'),'-GhostscriptPath',(Join-Path $env:LOCALAPPDATA 'WinPDFMergerDevCache/T09-gs-e84c278f46724e9a97dd8dbcdbb8d66f/ghostscript-10.08.0-x64/bin/gswin64c.exe'),'-PythonPath',(Join-Path $env:USERPROFILE '.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe'))
$work=Join-Path $repo ('tests/.work/T16-dirty-'+$Shell+'-ParametersNative-'+$Attempt+'-'+[Guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($work)
$start=New-Object Diagnostics.ProcessStartInfo;$start.FileName=$exe;$start.Arguments=ConvertTo-NativeArgumentString $argv;$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.RedirectStandardInput=$true;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;$start.StandardOutputEncoding=[Text.Encoding]::UTF8;$start.StandardErrorEncoding=[Text.Encoding]::UTF8
$modules=Join-Path ([IO.Path]::GetDirectoryName($exe)) 'Modules';$start.EnvironmentVariables['PSModulePath']=$modules
$launch=[ordered]@{ObservedAtUtc=[datetime]::UtcNow.ToString('o');CommitUnderTest=(& git -C $repo rev-parse HEAD);DirtyWorktree=(@(& git -C $repo status --porcelain=v1).Count -ne 0);Shell=$Shell;Executable=$exe;Arguments=$argv;PSModulePath=$modules;TestSourceSHA256=(Get-FileHash -LiteralPath (Join-Path $repo 'tests/cli/Parameters.Native.Tests.ps1') -Algorithm SHA256).Hash;EntrySHA256=(Get-FileHash -LiteralPath (Join-Path $repo 'WinPDFMerge.ps1') -Algorithm SHA256).Hash;HelperSHA256=(Get-FileHash -LiteralPath (Join-Path $repo 'src/WinPDFMerge.Helpers.ps1') -Algorithm SHA256).Hash;RunnerSHA256=(Get-FileHash -LiteralPath (Join-Path $repo 'tools/test/Invoke-Tests.ps1') -Algorithm SHA256).Hash;LauncherSHA256=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash}
[IO.File]::WriteAllText((Join-Path $work 'launch.json'),($launch|ConvertTo-Json -Depth 5),(New-Object Text.UTF8Encoding($false)))
$process=New-Object Diagnostics.Process;$process.StartInfo=$start
try{if(-not $process.Start()){throw 'Selected shell failed to start.'};$process.StandardInput.Close();$out=$process.StandardOutput.ReadToEndAsync();$err=$process.StandardError.ReadToEndAsync();Write-Output ('Smoke logs: '+$work);$process.WaitForExit();[IO.File]::WriteAllText((Join-Path $work 'stdout.txt'),$out.Result,(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText((Join-Path $work 'stderr.txt'),$err.Result,(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText((Join-Path $work 'exit-code.txt'),[string]$process.ExitCode);Write-Output $out.Result;Write-Output $err.Result;exit $process.ExitCode}finally{$process.Dispose()}
